# This file is NOT licensed under the GPLv3, which is the license for the rest
# of YouCompleteMe.
#
# Here's the license text for this file:
#
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org/>

import re
import os
import ycm_core


SOURCES = ['cpp', 'cxx', 'c', 'cc']
HEADERS = ['.h', '.hxx', '.hpp', '.hh']


def DirectoryOfThisScript():
  return os.path.dirname(os.path.abspath(__file__))


# These are the compilation flags that will be used in case there's no
# compilation database set (by default, one is not set).
# CHANGE THIS LIST OF FLAGS. YES, THIS IS THE DROID YOU HAVE BEEN LOOKING FOR.
flags = list()

# Set this to the absolute path to the folder (NOT the file!) containing the
# compile_commands.json file to use that instead of 'flags'. See here for
# more details: http://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# Most projects will NOT need to set this to anything; you can just change the
# 'flags' list of compilation flags. Notice that YCM itself uses that approach.
database_folder = os.path.join(DirectoryOfThisScript(), 'build')
database_file = os.path.join(database_folder, 'compile_commands.json')

if os.path.exists(database_folder):
  database = ycm_core.CompilationDatabase(database_folder)
else:
  database = None


def MakeAbsolute(flags, working_directory):
  if not working_directory:
    return list(flags)
  new_flags = []
  make_next_absolute = False
  path_flags = ['-isystem', '-I', '-iquote', '--sysroot=']
  for flag in flags:
    new_flag = flag

    if make_next_absolute:
      make_next_absolute = False
      if not flag.startswith('/'):
        new_flag = os.path.join(working_directory, flag)

    for path_flag in path_flags:
      if flag == path_flag:
        make_next_absolute = True
        break

      if flag.startswith(path_flag):
        path = flag[len(path_flag):]
        new_flag = path_flag + os.path.join(working_directory, path)
        break

    if new_flag:
      new_flags.append(new_flag)
  return new_flags


def IsHeaderFile(filename):
  extension = os.path.splitext(filename)[1]
  return extension in HEADERS


def GetCompilationInfoForFile(filename):
    # The compilation_commands.json file generated by CMake does not have
    # entries for header files. We try to find corresponding source file by
    # grepping for the base name. If one exists, the flags for that file
    # should be good enough.
    if IsHeaderFile(filename):
        p, fn = os.path.split(filename)
        fn, e = os.path.splitext(fn)
        r = r'"file": "(.*{0}\.(?:{1}))"'.format(fn, '|'.join(SOURCES))
        for line in open(database_file, 'r'):
            m = re.findall(r, line)
            if m:
                compilation_info = database.GetCompilationInfoForFile(m[0])
                if compilation_info.compiler_flags_:
                    return compilation_info
        return None
    return database.GetCompilationInfoForFile(filename)


def FlagsForFile(filename, **kwargs):
    flags = list()
    if database:
        compilation_info = GetCompilationInfoForFile(filename)
        if compilation_info:
            flags = MakeAbsolute(compilation_info.compiler_flags_,
                                 compilation_info.compiler_working_dir_)
    if not flags:
      relative_to = DirectoryOfThisScript()
      flags = MakeAbsolute(flags, relative_to)
    return {'flags': flags, 'do_cache': True}
